---
image: registry.gitlab.fpcomplete.com/fpco/default-build-image:17

stages:
  - lint
  - build
  - run

variables:
  PROJECT_NAME: "docker-ci-demo"
  VERSION_TAG: "${CI_BUILD_REF_SLUG}_${CI_PIPELINE_ID}"
  FROM_DOCKER: "from-dockerfile"
  FROM_BUILDAH: "from-buildah"
  BUILDAH_IMAGE: "${PROJECT_NAME}-${FROM_BUILDAH}"
  DOCKER_IMAGE: "${PROJECT_NAME}-${FROM_DOCKER}"
  CURRENT_BUILDAH: "${BUILDAH_IMAGE}:${VERSION_TAG}"
  CURRENT_DOCKER: "${DOCKER_IMAGE}:${VERSION_TAG}"

.anchors:
  - &REGISTRYLOGIN
    docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"

before_script:
  - sudo add-apt-repository --yes ppa:projectatomic/ppa
  - sudo apt-get update
  - sudo apt-get install --yes buildah skopeo jq

shellcheck:
  stage: lint
  script:
    - sudo apt-get install --yes shellcheck
    - make shellcheck

gitlab-ci-yml:
  stage: lint
  script:
    - sudo apt-get install --reinstall python-pkg-resources
    - sudo apt-get install --yes yamllint
    - yamllint .gitlab-ci.yml

oci-buildah:
  stage: build
  when: manual
  script:
    - echo 'Unimplemented'
    - exit 1
  only:
    - master

oci-dockerfile:
  stage: build
  when: manual
  script:
    - echo 'Unimplemented'
    - exit 1
  only:
    - master

docker-buildah:
  stage: build
  variables:
    LATEST_IMAGE: "${BUILDAH_IMAGE}:latest"
  script:
    - sudo make docker-from-buildah
    - sudo buildah push
        --creds=gitlab-ci-token:${CI_BUILD_TOKEN}
        ${CURRENT_BUILDAH}
        docker://${CI_REGISTRY}/${CURRENT_BUILDAH}
    - docker tag "${CURRENT_BUILDAH}" "${LATEST_IMAGE}"
    - docker push "${LATEST_IMAGE}"
    - skopeo inspect docker://${CI_REGISTRY}/${CURRENT_BUILDAH} |
        jq -r '.Digest'
        > 'docker-buildah.sha256'
  only:
    - master

docker-dockerfile:
  stage: build
  variables:
    LATEST_IMAGE: "${DOCKER_IMAGE}:latest"
  script:
    - docker build -t "${CURRENT_DOCKER}" scripts/build
    - *REGISTRYLOGIN
    - docker push "${CURRENT_DOCKER}"
    - docker tag "${CURRENT_DOCKER}" "${LATEST_IMAGE}"
    - docker push "${LATEST_IMAGE}"
    - skopeo inspect docker://${CI_REGISTRY/${CURRENT_DOCKER} |
        jq -r '.Digest'
        > 'docker-dockerfile.sha256'
  only:
    - master

buildah-image:
  stage: run
  script:
    - *REGISTRYLOGIN
    - docker pull "${DOCKER_IMAGE}@$(cat docker-buildah.sha256)"
    - c=$(docker run --detach "${DOCKER_IMAGE}@$(cat docker-buildah.sha256)")
    - docker stop "${c}"
    - docker rm "${c}"
  only:
    - master

docker-image:
  stage: run
  script:
    - *REGISTRYLOGIN
    - docker pull "${DOCKER_IMAGE}@$(cat docker-dockerfile.sha256)"
    - c=$(docker run --detach "${DOCKER_IMAGE}@$(cat docker-dockerfile.sha256")
    - docker stop "${c}"
    - docker rm "${c}"
  only:
    - master
