---
stages:
  - lint
  - build

variables:
  PROJECT_NAME: "rkt-demo"
  RKT_VERSION: "1.29.0"

before_script:
  - 'wget https://github.com/rkt/rkt/releases/download/v${RKT_VERSION}/rkt_${RKT_VERSION}-1_amd64.deb'
  - 'sudo apt install rkt_${RKT_VERSION}-1_amd64.deb'
  - 'sudo add-apt-repository --yes ppa:projectatomic/ppa'
  - 'sudo apt update'
  - 'sudo apt install buildah'

shellcheck:
  stage: lint
  script:
    - 'sudo apt install --yes shellcheck'
    - 'make shellcheck'

oci-from-buildah:
  stage: build
  script:
    - 'make oci-from-buildah'
  only:
    - master

oci-from-dockerfile:
  stage: build
  script:
    - 'make oci-from-dockerfile'
  only:
    - master

docker-from-buildah:
  stage: build
  script:
    - 'make docker-from-buildah'
  only:
    - master

docker-from-dockerfile:
  stage: build
  script:
    - 'make docker-from-dockerfile'
  only:
    - master
