---
image: registry.gitlab.fpcomplete.com/fpco/default-build-image:1009

stages:
  - lint
  - build
  - run

variables:
  PROJECT: rkt-demo

.anchors:
  - &REGISTRYLOGIN
    docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"

shellcheck:
  stage: lint
  variables:
    IMAGE: koalaman/shellcheck
    SHA: sha256:22bd736eb6c3cb8e15b888cf3d244839cc5bb35a5858feeb61a9e9bbfd7c7337
  script:
    - docker pull "${IMAGE}@${SHA}"
    - docker run -v "${PWD}:/mnt" "${IMAGE}@${SHA}" $(find -name '*.sh')

yamllint:
  stage: lint
  variables:
    IMAGE: dcycle/yaml-lint
    SHA: sha256:22b33626d57e990399d38ecc648884fb44ab9638eb1d3e1a2ab835864427ec20
  script:
    - docker pull "${IMAGE}@${SHA}"
    - docker run -v "${PWD}/:/app"
                    "${IMAGE}@{SHA}"
                    $(find -name '*.yml' -o -name '*.yaml')

dockerfile:
  stage: build
  variables:
    IMAGE: "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_SLUG}_${CI_PIPELINE_ID}"
    LATEST: "${CI_REGISTRY_IMAGE}:latest"
  script:
    - docker build -t "${IMAGE}" scripts/build
    - *REGISTRYLOGIN
    - docker push "${IMAGE}"
    - docker tag "${IMAGE}" "${LATEST}"
    - docker push "${LATEST}"
    - docker inspect "${IMAGE}"
        | jq -r '.[0] | .RepoDigests[0]'
        > '${PROJECT}.sha256'
  artifacts:
    paths:
      - '${PROJECT}.sha256'

docker:
  stage: run
  script:
    - *REGISTRYLOGIN
    - docker pull "$(cat ${PROJECT}.sha256)"
    - c=$(docker run
            --detach "$(cat ${PROJECT}.sha256)")
    - docker stop "${c}"
    - docker rm "${c}"
