---
image: registry.gitlab.fpcomplete.com/fpco/default-build-image:17

stages:
  - lint
  - build
  - run

variables:
  PROJECT_NAME: "docker-ci-demo"
  BUILDAH_IMAGE: "docker-ci-demo-from-buildah"
  DOCKER_IMAGE: "docker-ci-demo-from-docker"

.anchors:
  - &REGISTRYLOGIN
    docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"

before_script:
  - sudo add-apt-repository --yes ppa:projectatomic/ppa
  - sudo apt-get update
  - sudo apt-get install --yes buildah skopeo jq

shellcheck:
  stage: lint
  script:
    - sudo apt-get install --yes shellcheck
    - make shellcheck

gitlab-ci-yml:
  stage: lint
  script:
    - sudo apt-get install --reinstall python3-pkg-resources
    - sudo apt-get install --yes yamllint
    - yamllint .gitlab-ci.yml

oci-buildah:
  stage: build
  when: manual
  script:
    - echo 'Unimplemented'
    - exit 1
  only:
    - master

oci-dockerfile:
  stage: build
  when: manual
  script:
    - echo 'Unimplemented'
    - exit 1
  only:
    - master

docker-buildah:
  stage: build
  variables:
    IMAGE: "${BUILDAH_IMAGE}:${CI_BUILD_REF_SLUG}_${CI_PIPELINE_ID}"
    LATEST: "${BUILDAH_IMAGE}:latest"
  script:
    - sudo make docker-from-buildah
    - sudo buildah push
        --creds="gitlab-ci-token:${CI_BUILD_TOKEN}"
        "${IMAGE}"
        "docker://${CI_REGISTRY}/${IMAGE}"
    - docker tag "${IMAGE}" "${LATEST}"
    - docker push "${LATEST}"
    - skopeo inspect "docker://${CI_REGISTRY}/${IMAGE}" |
        jq -r '.Digest'
        > 'docker-buildah.sha256'
  only:
    - master

docker-dockerfile:
  stage: build
  variables:
    IMAGE: "${DOCKER_IMAGE}:${CI_BUILD_REF_SLUG}_${CI_PIPELINE_ID}"
    LATEST: "${DOCKER_IMAGE}:latest"
  script:
    - docker build -t "${IMAGE}" scripts/build
    - *REGISTRYLOGIN
    - docker push "${IMAGE}"
    - docker tag "${IMAGE}" "${LATEST}"
    - docker push "${LATEST}"
    - skopeo inspect "docker://${CI_REGISTRY}/${IMAGE}" |
        jq -r '.Digest'
        > 'docker-dockerfile.sha256'
  only:
    - master

buildah-image:
  stage: run
  script:
    - *REGISTRYLOGIN
    - docker pull "${BUILDAH_IMAGE}@$(cat docker-buildah.sha256)"
    - c=$(docker run --detach "${BUILDAH_IMAGE}@$(cat docker-buildah.sha256)")
    - docker stop "${c}"
    - docker rm "${c}"
  only:
    - master

docker-image:
  stage: run
  script:
    - *REGISTRYLOGIN
    - docker pull "${DOCKER_IMAGE}@$(cat docker-dockerfile.sha256)"
    - c=$(docker run --detach "${DOCKER_IMAGE}@$(cat docker-dockerfile.sha256")
    - docker stop "${c}"
    - docker rm "${c}"
  only:
    - master
