---
image: registry.gitlab.fpcomplete.com/fpco/default-build-image:1009

stages:
  - lint
  - build
  - run

.anchors:
  - &REGISTRYLOGIN
    docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"

before_script:
  - add-apt-repository --yes ppa:projectatomic/ppa
  - apt-get update
  - apt-get install --yes buildah skopeo jq

shellcheck:
  stage: lint
  script:
    - apt-get install --yes shellcheck
    - make shellcheck

gitlab-ci-yml:
  stage: lint
  script:
    - apt-get install --reinstall python3-pkg-resources
    - apt-get install --yes yamllint
    - yamllint .gitlab-ci.yml

dockerfile:
  stage: build
  variables:
    IMAGE: "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_SLUG}_${CI_PIPELINE_ID}"
    LATEST: "${CI_REGISTRY_IMAGE}:latest"
  script:
    - docker build -t "${IMAGE}" scripts/build
    - *REGISTRYLOGIN
    - docker push "${IMAGE}"
    - docker tag "${IMAGE}" "${LATEST}"
    - docker push "${LATEST}"
    - docker inspect "${IMAGE}"
        | jq -r '.[0] | .RepoDigests[0]'
        > 'docker-dockerfile.sha256'
  artifacts:
    paths:
      - docker-dockerfile.sha256
    expire_in: 1 day
  only:
    - master

docker-image:
  stage: run
  script:
    - *REGISTRYLOGIN
    - docker pull "$(cat docker-dockerfile.sha256)"
    - c=$(docker run
            --detach "$(cat docker-dockerfile.sha256)")
    - docker stop "${c}"
    - docker rm "${c}"
  only:
    - master
